### ISSUE TITLE
Add WXRC: section

### ISSUE THREAD

**Issue by ghost** [KeyWorksRW/ttBld#217]
### Description:
The **wxrc.exe** utility that's part of wxWidgets can be used to generate either (or both) .cpp and .h files. In both cases, it would be helpful to get the commands into the ninja scripts so that if a .xrc file is modified, then running the ninja script will regenerate any .cpp/.h file that **wxrc** creates as well as updating any dependencies on those files.

### Issue Type:
- [ ] Bug report
- [x] Feature request
- [ ] Design change request
- [ ] Other

**Comment by KeyWorksRW** [comment]
This issue was created before the **wxUiEditor** project got underway. With that project now in alpha state and working well enough to use for _all_ KeyWorks projects that use **wxWidgets**, it's hard to imagine trying to create/maintain a XRC file by hand. I'm not adverse to adding this, but only if someone actually needs it. :-)
